### PR TITLE
[BCT-2499] Use marketing-build-tools for build process

### PR DESCRIPTION
**Pull request by conwaydev**
## Updates

* Updates build process to use MBT instead of the default dev dependencies

### CODE REVIEW

**Review by jritterbush — COMMENTED** [review]
@conwaydev when I pull down this branch and run `yarn build`, there are a bunch of changes to the dist files. Should those builds match the ones you committed?

```
        modified:   assets/css/frontend.min.css
        modified:   assets/css/frontend.min.css.map
        modified:   assets/css/sidebar.min.css
        modified:   assets/css/sidebar.min.css.map
        modified:   assets/js/dist/admin.js
        modified:   assets/js/dist/canvas.js
        modified:   assets/js/dist/frontend.js
        modified:   assets/js/dist/sidebar.js
        modified:   assets/js/dist/tinymce.js
```

**Comment by conwaydev** [comment]
The JS files should definitely have changes (just how webpack outputs the "dev" build versus browserify), but you shouldnt see the css changes, those should be ignored?

**Comment by jritterbush** [comment]
**For the CSS:** You might need to flush them from the git index since they were already tracked: https://stackoverflow.com/a/19095988

**For the dev JS:** Why will they always appear as changes? Shouldn't running `yarn develop` on this be the same every time based on the source files and webpack config supplied?

**Comment by conwaydev** [comment]
@jritterbush I'm dumb i didn't commit the files, go ahead and pull em down

**Review by jritterbush — APPROVED** [review]
All good now! Thanks for the fixes.

**Comment by conwaydev** [comment]
those were good catches, thanks

**Pull request merged**
